# Generated by Django 3.0.2 on 2020-01-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbageimage', models.ImageField(default='', upload_to='wastemmt/images')),
            ],
        ),
    ]
