# Generated by Django 3.0.2 on 2020-01-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastemmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='garbageimage',
            field=models.FileField(default='', upload_to='wastemmt/images'),
        ),
    ]
