# Generated by Django 3.0.2 on 2020-01-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastemmt', '0003_logcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcredential',
            name='passwords',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='logcredential',
            name='usernames',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
