# Generated by Django 3.0.2 on 2020-01-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastemmt', '0004_auto_20200120_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='logincredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameslogin', models.CharField(max_length=50, unique=True)),
                ('passwordslogin', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
