# Generated by Django 3.0.2 on 2020-01-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastemmt', '0005_logincredentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logincredentials',
        ),
        migrations.AlterField(
            model_name='images',
            name='garbageimage',
            field=models.ImageField(default='', upload_to='wastemmt/images'),
        ),
    ]
