# Generated by Django 3.0.2 on 2020-01-20 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wastemmt', '0007_images1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images1',
        ),
    ]
