# Generated by Django 2.2.9 on 2020-01-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastemmt', '0008_delete_images1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='garbageimage',
            field=models.FileField(default='', upload_to='wastemmt/images'),
        ),
    ]
