# Generated by Django 2.2.9 on 2020-01-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastemmt', '0009_auto_20200120_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='garbageimage',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
